# Generated by Django 2.2.1 on 2019-06-13 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='channel',
            fields=[
                ('label', models.TextField(default='Label for channel', max_length=100)),
                ('fieldId', models.TextField(default='0x9de881585bc74214', editable=False, primary_key=True, serialize=False, unique=True)),
                ('mqttLink', models.TextField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mqttBroker',
            fields=[
                ('description', models.TextField(default=None, max_length=100)),
                ('mqttAddr', models.TextField(default=None, max_length=200, primary_key=True, serialize=False)),
                ('mqttUserName', models.TextField(default=None)),
                ('mqttPassword', models.TextField(default=None)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='channelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.channel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='mqttBroker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.mqttBroker'),
        ),
        migrations.AddField(
            model_name='channel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
