# Generated by Django 2.2.1 on 2019-06-12 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='channel',
            fields=[
                ('fieldId', models.TextField(default='0xd53e557fb1784b2e', editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='mqttBroker',
            fields=[
                ('description', models.TextField(default=None, max_length=100)),
                ('mqttLink', models.TextField(default=None, max_length=200, primary_key=True, serialize=False)),
                ('mqttUserName', models.TextField(default=None)),
                ('mqttPassword', models.TextField(default=None)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='dataContent',
        ),
        migrations.DeleteModel(
            name='dataField',
        ),
        migrations.AddField(
            model_name='channel',
            name='mqttBroker',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='data.mqttBroker'),
        ),
        migrations.AddField(
            model_name='channel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
