# Generated by Django 2.2.1 on 2019-06-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='key',
            field=models.TextField(default='0xec760bb692644612', editable=False),
        ),
    ]
