# Generated by Django 2.2.1 on 2019-06-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='fieldId',
            field=models.TextField(default='0x1c8a0842', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
