# Generated by Django 2.2.1 on 2019-06-12 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190612_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='fieldId',
            field=models.TextField(default='0x6cf31c06593448b3', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='channelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.channel')),
            ],
        ),
    ]
