# Generated by Django 2.2.1 on 2019-06-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190613_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mqttbroker',
            old_name='description',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='channel',
            name='fieldId',
            field=models.TextField(default='0xa2cb5bc5e58c49f1', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
