# Generated by Django 2.2.1 on 2019-06-12 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190612_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='fieldId',
            field=models.TextField(default='0x3348a0416e454107', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='mqttBroker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.mqttBroker'),
        ),
    ]
