# Generated by Django 2.2.1 on 2019-06-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190612_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='label',
            field=models.TextField(default='Label for channel', max_length=100),
        ),
        migrations.AlterField(
            model_name='channel',
            name='fieldId',
            field=models.TextField(default='0xf7cfa25329c4426e', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
