# Generated by Django 2.2.1 on 2019-06-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190620_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='key',
            field=models.TextField(default=None, unique=True),
        ),
    ]
