# Generated by Django 2.2.1 on 2019-06-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190620_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='key',
            field=models.TextField(
                default='0x21a3f221a7d84acb', editable=False, unique=True),
        ),
    ]
